/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/EmailConfirmationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/main/MainScreen`; params?: Router.UnknownInputParams; } | { pathname: `/main/SearchPage`; params?: Router.UnknownInputParams; } | { pathname: `/main/stylesMain`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AuthStack`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/MainStack`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/RootNavigator`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/EmailConfirmationScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/WelcomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/main/MainScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/main/SearchPage`; params?: Router.UnknownOutputParams; } | { pathname: `/main/stylesMain`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/AuthStack`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/MainStack`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/RootNavigator`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/EmailConfirmationScreen${`?${string}` | `#${string}` | ''}` | `/auth/LoginScreen${`?${string}` | `#${string}` | ''}` | `/auth/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/auth/WelcomeScreen${`?${string}` | `#${string}` | ''}` | `/main/MainScreen${`?${string}` | `#${string}` | ''}` | `/main/SearchPage${`?${string}` | `#${string}` | ''}` | `/main/stylesMain${`?${string}` | `#${string}` | ''}` | `/navigation/AuthStack${`?${string}` | `#${string}` | ''}` | `/navigation/MainStack${`?${string}` | `#${string}` | ''}` | `/navigation/RootNavigator${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/EmailConfirmationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/main/MainScreen`; params?: Router.UnknownInputParams; } | { pathname: `/main/SearchPage`; params?: Router.UnknownInputParams; } | { pathname: `/main/stylesMain`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AuthStack`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/MainStack`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/RootNavigator`; params?: Router.UnknownInputParams; };
    }
  }
}
